package com.haier.greendao.autoputgreendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.haier.greendao.demogreendao.bean.Member;
import com.haier.greendao.demogreendao.bean.SecondBean;

import com.haier.greendao.autoputgreendao.MemberDao;
import com.haier.greendao.autoputgreendao.SecondBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memberDaoConfig;
    private final DaoConfig secondBeanDaoConfig;

    private final MemberDao memberDao;
    private final SecondBeanDao secondBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        secondBeanDaoConfig = daoConfigMap.get(SecondBeanDao.class).clone();
        secondBeanDaoConfig.initIdentityScope(type);

        memberDao = new MemberDao(memberDaoConfig, this);
        secondBeanDao = new SecondBeanDao(secondBeanDaoConfig, this);

        registerDao(Member.class, memberDao);
        registerDao(SecondBean.class, secondBeanDao);
    }
    
    public void clear() {
        memberDaoConfig.clearIdentityScope();
        secondBeanDaoConfig.clearIdentityScope();
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

    public SecondBeanDao getSecondBeanDao() {
        return secondBeanDao;
    }

}
